spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FixLife_CIA103?serverTimezone=Asia/Taipei
    username: root
    password: 666666
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
#      password: xxxx //沒有設定密碼
      timeout: 60000

#  security:
#    user:
#      name: ""
#      password: ""

  #關閉自動裝配
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    enabled: true
    cache: true
    prefix: classpath:/templates
    suffix: .html

# 伺服器配置
server:
  port: 8080
#  servlet:
#    context-path: /start

#logging:
#  level:
#    org.springframework: DEBUG

